---
# tasks file for ansible-role-vlans_on_trunk

- include: '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'

- debug:
    msg: "ansible_virtualization_type = {{ ansible_virtualization_type }}, ansible_virtualization_role = {{ ansible_virtualization_role }}"

# - name: Enable kernel modules - VLAN
#   modprobe:
#     name: '8021q'
#     state: present