---
# tasks file for ansible-role-vlans_on_trunk

- include: '{{ ansible_distribution | lower }}_{{ ansible_distribution_version }}.yml'

- name: Enable kernel modules - VLAN
  modprobe:
    name: '8021q'
    state: present