---
# tasks file for ansible-role-vlans_on_trunk

- name: Install VLAN-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'vlan'
    - 'ifenslave'
    - 'python-lxml'