- name: Install VLAN-related packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    update_cache: 'yes'
  with_items:
    - 'vlan'
    - 'ifenslave'
    - 'python-lxml'
  when: ansible_virtualization_type != 'docker'


- name: Configure VLAN interfaces on trunking ports
  template:
    src: templates/ubuntu_vlan_if.cfg.j2
    dest: /etc/network/interfaces.d/{{ vlan_on_trunk_TrunkInterfaceName }}.{{ item.vlan_id }}.cfg
  with_items: '{{ vlan_on_trunk_MultiVlanConfig }}'
  notify: restart networking.service
  when: ansible_virtualization_type != 'docker'